// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCziFIHiPP6Ktt4f2Y-KZKzqpPxik7Flj4',
    appId: '1:730093450926:web:8658656850b5d34787df3f',
    messagingSenderId: '730093450926',
    projectId: 'flashcards-d8007',
    authDomain: 'flashcards-d8007.firebaseapp.com',
    databaseURL: 'https://flashcards-d8007-default-rtdb.firebaseio.com',
    storageBucket: 'flashcards-d8007.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWNS9hEP90d3TbjMkFlxWYk3hkGRtVNlA',
    appId: '1:730093450926:android:103a42fe940c873987df3f',
    messagingSenderId: '730093450926',
    projectId: 'flashcards-d8007',
    databaseURL: 'https://flashcards-d8007-default-rtdb.firebaseio.com',
    storageBucket: 'flashcards-d8007.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBW9VuMRw5Mx5Z6jacwFbujzk89kDPot78',
    appId: '1:730093450926:ios:7bb6090659fe377787df3f',
    messagingSenderId: '730093450926',
    projectId: 'flashcards-d8007',
    databaseURL: 'https://flashcards-d8007-default-rtdb.firebaseio.com',
    storageBucket: 'flashcards-d8007.firebasestorage.app',
    iosClientId: '730093450926-g2fi0mut0fnvihfsode9ud9sl2pn2a1n.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizapp',
  );
}
